recompress uploaded schematics with zopfli
Create-Schematics/Create-Schematics pull request #6
Opened 2023-12-30 00:11 UTC by rhysdh540

since nbt files are compressed with gzip, they can be re-compressed with a tool that, well, *compresses better* (in this case [zopfli](https://github.com/zopfli-rs/zopfli)). Currently, it uses 500 zopfli iterations, or 100 if the file is larger than 20 kb. If any errors occur, it just skips the compression step.

 I have no clue how to get this set up correctly on my computer so I’m unable to test it, and I would appreciate any suggestions (hence why this is a draft)

pros:
 - it’s cool
 - less time spent downloading schematics
 
cons:
 - zopfli is a very expensive algorithm that takes a long time to compress data (can be lessened by using less iterations, at the cost of compression ratio)

2023-12-30 00:32 UTC, Rabbitminers commented
Hey! Thanks for helping out, we really appreciate it :)

I'll look into bench marking this so we can see what a good iteration count could be or perhaps swapping out the algorithm for a cheaper one if not. Perhaps also adding this to image uploads as well instead of to x% of the original quality. 

As for getting this to run locally for testing have a look at the README but the shortened version is installer docker (and docker compose if it's not included already) then run `docker compose up` in the root directory to set up the database and redis, then `cargo run server` in the backend directory.

2023-12-30 03:50 UTC, rhysdh540 commented
> adding this to image uploads
Perhaps converting all the image uploads to webp would be beneficial?

2023-12-30 14:49 UTC, Rabbitminers commented
> Perhaps converting all the image uploads to webp would be beneficial?

That's the current plan although the [image crate](https://docs.rs/image/latest/image/) doesn't natively support encoding to webp so we need to look into an alternative encoder like that from the [webp crate](https://docs.rs/webp/latest/webp/struct.Encoder.html)

2024-01-02 15:45 UTC, Rabbitminers commented
Following up on this I've done some testing and the results are useful but do show that there's quite a performance decrease (these are ran on a release build of [a fork](https://github.com/rabbitminers/nbt-compressor) of the command line wrapper you wrote) 

On a fairly small schematic (a little less than 4kb) I tried iteration counts from 10 to 500 in steps of 10 here's a sample of the data

`INFO nbt_compress: iterations=10 elapsed=184.924101ms original_size=3796 compressed_size=3710 saved_space=86`

`INFO nbt_compress: iterations=10 elapsed=184.924101ms original_size=3796 compressed_size=3710 saved_space=86`

`INFO nbt_compress: iterations=500 elapsed=709.489408ms original_size=3796 compressed_size=3710 saved_space=86`

So you see we have quite heavy performance hit even at 10 iterations given currently schematic uploads happen in at most a few milliseconds without compression. An interesting thing to note is that we see no change in file size reduction at all between 10 and 500 iterations (86 bytes). 

I tried again with a much larger schematic about (163.5kb) with the same iteration count

`INFO nbt_compress: iterations=10 elapsed=1.164058641s original_size=167401 compressed_size=128160 saved_space=39241`

`INFO nbt_compress: iterations=250 elapsed=10.193499235s original_size=167401 compressed_size=128120 saved_space=39281`

`INFO nbt_compress: iterations=500 elapsed=17.848809262s original_size=167401 compressed_size=128159 saved_space=3924`

This time we do see  a change in file size between iterations but also a very severe decrease in performance

2024-01-02 21:36 UTC, rhysdh540 commented
Pretty much complete, webp conversion isn't lossless but it at least works for all the images I threw at it.

2024-01-02 21:52 UTC, Rabbitminers requested changes

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +    let contents = match decompress(input.clone()) {
Borrow the input vector here to avoid needing to clone it

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +fn decompress(stuff: Vec<u8>) -> io::Result<Vec<u8>> {
Maybe rename `stuff` to data to be consistent with the compress function

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +    compress(contents).unwrap_or_else(|_| input)
Perhaps return an option here instead instead of needing to handle defaulting to the original input twice

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +        Err(_) => Err(Error::new(io::ErrorKind::InvalidData, "Invalid gzip data"))
For consistency and to try and avoid loosing information in the original error maybe use an anyhow error return type here.

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +    let mut compressor = Compressor::new(CompressionLvl::new(12).unwrap());
Even if this is very unlikely to cause a problem ideally we don't want to use unwrap or any other fallback that leads to a panic in production

2024-01-02 21:52 UTC, Rabbitminers commented on backend/benches/file_optimisation.rs
> +    println!("{}: {} -> {} (saved {})", name, contents.len(), smallest, contents.len() - smallest);
Use tracing logging here for consistency

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +        let webp = encoder.encode(100f32);
Maybe reduce this a little bit, we probably don't need to store these images at full quality

2024-01-02 21:52 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +        let img = image::load_from_memory(&image.contents)
We may want to look into moving this to a separate thread as well as using tokio's file system library for asynchronous writing although that might be out of scope for this pr

2024-01-02 23:44 UTC, rhysdh540 commented on backend/src/storage/upload.rs
> +        let webp = encoder.encode(100f32);
Which quality would you suggest? WebP is already pretty efficient with file size, even at full quality

2024-01-03 02:22 UTC, rhysdh540 commented on backend/src/storage/upload.rs
> +        Err(_) => Err(Error::new(io::ErrorKind::InvalidData, "Invalid gzip data"))
The error types of the results that these return don't implement `std::error::Error` which is required for anyhow result types, making them kind of hard to map correctly.

2024-01-03 02:23 UTC, rhysdh540 commented on backend/benches/file_optimisation.rs
> +    println!("{}: {} -> {} (saved {})", name, contents.len(), smallest, contents.len() - smallest);
What else do I need to add to get the tracing to actually print stuff?

2024-01-03 12:51 UTC, Rabbitminers commented on backend/src/storage/upload.rs
> +        let webp = encoder.encode(100f32);
90 Is probably fine, if file size is a problem we can reduce it in the future

2024-01-03 12:53 UTC, Rabbitminers commented on backend/benches/file_optimisation.rs
> +    println!("{}: {} -> {} (saved {})", name, contents.len(), smallest, contents.len() - smallest);
You need to call `tracing_subscriber::fmt::init();` to display to standard output

2024-01-03 13:42 UTC, rhysdh540 commented on backend/benches/file_optimisation.rs
> +    println!("{}: {} -> {} (saved {})", name, contents.len(), smallest, contents.len() - smallest);
I've tried that, but it still doesn't print. (I wrapped it in a `std::sync::Once` because calling it more than once causes it to panic).

2024-01-05 10:38 UTC, merged